AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  outlook-schedule-fetcher-sample

  Sample SAM Template for outlook-schedule-fetcher-sample

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Parameters:
  AzureTenantID:
    Type: String
  AzureAppID:
    Type: String
  AzureAppSecret:
    Type: String
  AzureUserPrincipalName:
    Type: String

Resources:
  OutlookScheduleFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: outlook_schedule_fetcher/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Environment:
        Variables:
          AZURE_TENANT_ID: !Ref AzureTenantID
          AZURE_APP_ID: !Ref AzureAppID
          AZURE_APP_SECRET: !Ref AzureAppSecret
          AZURE_USER_PRINCIPAL_NAME: !Ref AzureUserPrincipalName
      Architectures:
        - x86_64
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(* * ? * * *)
            ScheduleExpressionTimezone: Japan

Outputs:
  OutlookScheduleFetcherFunction:
    Description: "Outlook Schedule Fetcher Lambda Function ARN"
    Value: !GetAtt OutlookScheduleFetcherFunction.Arn
  OutlookScheduleFetcherFunctionIamRole:
    Description: "Implicit IAM Role created for Outlook Schedule Fecther function"
    Value: !GetAtt OutlookScheduleFetcherFunctionRole.Arn
